apiVersion: v1
kind: Pod
metadata:
  name: debug-crypto
  namespace: terraflow-app
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: crypto-storage
      mountPath: /crypto-config
  volumes:
  - name: crypto-storage
    persistentVolumeClaim:
      claimName: fabric-crypto-pvc
  restartPolicy: Never