apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-couchdb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/fabric-couchdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-couchdb-pvc
  namespace: terraflow-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi