apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-peer-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/fabric-peer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-peer-pvc
  namespace: terraflow-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi