module.exports = {
  QUEUES: {
    LAND_REGISTRY: 'queue_landregistry',
    DOCUMENTS: 'queue_documents'
  },
  EVENT_TYPES: {
    DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    DOCUMENT_FAILED: 'DOCUMENT_FAILED',
    ROLLBACK_TRANSACTION: 'ROLLBACK_TRANSACTION',
    PAYMENT_STATUS_UPDATE: 'PAYMENT_STATUS_UPDATE'
  },
  TABLES: {
    LAND_TITLES: 'land_titles'
  },
  STATUS: {
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE', 
    FAILED: 'FAILED'
  }
};