module.exports = {
  QUEUES: {
    LAND_REGISTRY: 'queue_landregistry',
    DOCUMENTS: 'queue_documents'
  },
  EVENT_TYPES: {
    DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    DOCUMENT_FAILED: 'DOCUMENT_FAILED',
    ROLLBACK_TRANSACTION: 'ROLLBACK_TRANSACTION'
  },
  TABLES: {
    LAND_TITLES: 'land_titles'
  },
  STATUS: {
    PENDING: 'PENDING',
    PENDING_DOCUMENTS: 'PENDING_DOCUMENTS',
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    PENDING_PAYMENT: 'PENDING_PAYMENT',
    PROCESSING: 'PROCESSING',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED'
  }
};